name: frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  collection: ^1.19.1
  desktop_drop: ^0.6.1
  dio: ^5.8.0+1
  dotted_border: ^3.1.0
  file_picker: ^10.2.1
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  go_router: ^16.1.0
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  retrofit: ^4.7.0
  shadcn_flutter: ^0.0.37
  file_saver: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  injectable_generator: ^2.8.1
  retrofit_generator: ^10.0.1
flutter:
  uses-material-design: true