name: frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  retrofit: ^4.7.0
  shadcn_flutter: ^0.0.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  injectable_generator: ^2.8.1
  retrofit_generator: ^10.0.1
flutter:
  uses-material-design: true