services:
  backend:
    build:
      context: backend
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
  frontend:
    build:
      context: frontend
    ports:
      - "8080:8080"

