name: Build Docker Image

env:
  BE_DOCKER_IMAGE: goconvert-it-backend
  FE_DOCKER_IMAGE: goconvert-it-frontend
  DOCKER_USER: specialfish9
  DOCKER_USERNAME: specialfish9
  DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Build and push Docker image Backend
      uses: docker/build-push-action@v5
      with:
        context: backend
        push: true
        tags: |
          ${{ env.DOCKER_USER }}/${{ env.BE_DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_USER }}/${{ env.BE_DOCKER_IMAGE }}:${{ steps.date.outputs.date }} 

    - name: Build and push Docker image Frontend
      uses: docker/build-push-action@v5
      with:
        context: frontend
        push: true
        tags: |
          ${{ env.DOCKER_USER }}/${{ env.FE_DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_USER }}/${{ env.FE_DOCKER_IMAGE }}:${{ steps.date.outputs.date }} 
