name: Build Docker Image

env:
  BE_DOCKER_IMAGE: goconvert-it-backend
  #FE_DOCKER_IMAGE: spiderfront
  DOCKER_USER: specialfish9
  DOCKER_USERNAME: specialfish9
  DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PWD

    - name: Build and push Docker backend image
      run: docker build --push -t ${{ env.DOCKER_USER }}/${{ env.BE_DOCKER_IMAGE }}:latest -t ${{ env.DOCKER_USER }}/${{ env.BE_DOCKER_IMAGE }}:${{ steps.date.outputs.date }} backend

    # - name: Build and push Docker frontend image
    #   run: docker build --push -t ${{ env.DOCKER_USER }}/${{ env.FE_DOCKER_IMAGE }}:latest -t ${{ env.DOCKER_USER }}/${{ env.FE_DOCKER_IMAGE }}:${{ steps.date.outputs.date }} frontend
